version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: carbon_user
      POSTGRES_PASSWORD: carbon_password
      POSTGRES_DB: carboniq_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
